add_newline = false

# format = """$all\
# $line_break \
# $jobs\
# $character"""

[character]
success_symbol = "[%](bold green)"
error_symbol = "[%](bold red)"

[status]
symbol = "ðŸ’¥:"
disabled = false

[jobs]
symbol = "ðŸš€"
threshold = 1

[time]
disabled = false

## deprecated

# [custom.docker]
# command = "hostname | awk -F. '{print $1}'"
# when = """grep -s docker /proc/1/cgroup"""
# format = "ðŸ‹ [$output>]($style) "
# style = "bold blue"
#
# [custom.mac]
# when = """ test "Darwin" = "$(uname -s)" """
# format = "\uF302"
#
# [custom.ubuntu]
# when = """ test "$(grep -s '^ID=' /etc/os-release | awk -F= '{print $2}')" = "ubuntu" """
# format = "\uF31B"
#
# [custom.kali]
# when = """ test "$(grep -s '^ID=' /etc/os-release | awk -F= '{print $2}')" = "kali" """
# format = "\uF316"
