add_newline = true

format = """$all$time$jobs[docker](bold blue)ğŸ‹$character"""

[conda]
# symbol = "â­•"
symbol = "ğŸ…’ "

[jobs]
symbol = "âš™ï¸ "
threshold = 1

[time]
disabled = false
format = '[â±ï¸ #$time]($style) '
time_format = "%T"
utc_time_offset = "+8"
