add_newline = true

format = """
$all\
${custom.docker}\
${custom.mac}\
${custom.ubuntu}\
${custom.kali}\
$line_break\
$time\
$jobs$character"""

[character]
success_symbol = "[ï˜½](bold green)"
error_symbol = "[âœ—](bold red)"

[username]
format = "[$user]($style)@"

[status]
symbol = "ï  "
disabled = false

[jobs]
symbol = "âœ¨"
threshold = 1

[time]
disabled = false
format = "[$time]($style) "
time_format = "%T"
utc_time_offset = "+8"

[custom.docker]
command = "hostname | awk -F. '{print $1}'"
when = """grep -s docker /proc/1/cgroup"""
format = "ðŸ‹ [$output>]($style) "
style = "bold blue"

[custom.mac]
when = """ test "Darwin" = "$(uname -s)" """
format = "\uF302"

[custom.ubuntu]
when = """ test "$(grep -s '^ID=' /etc/os-release | awk -F= '{print $2}')" = "ubuntu" """
format = "\uF31B"

[custom.kali]
when = """ test "$(grep -s '^ID=' /etc/os-release | awk -F= '{print $2}')" = "kali" """
format = "\uF316"
