add_newline = true

format = """${custom.docker}$all$time\
${custom.mac}\
${custom.ubuntu}\
${custom.kali}\
$jobs$character"""

[conda]
symbol = "ðŸ…’ "

[jobs]
symbol = "\uF0AE "
threshold = 1

[time]
disabled = false
format = "[\uF651 $time]($style) "
time_format = "%T"
utc_time_offset = "+8"

[custom.docker]
command = "hostname | awk -F. '{print $1}'"
when = """grep -s docker /proc/1/cgroup"""
format = "ðŸ‹ [$output>]($style) "
style = "bold blue"

[custom.mac]
when = """ test "Darwin" = "$(uname -s)" """
format = "[mac](bold white)\uF302 "

[custom.ubuntu]
when = """ test "$(grep -s '^ID=' /etc/os-release | awk -F= '{print $2}')" = "ubuntu" """
format = "[ubuntu](bold purple)\uF31B "

[custom.kali]
when = """ test "$(grep -s '^ID=' /etc/os-release | awk -F= '{print $2}')" = "kali" """
format = "[kali](bold red)\uF316 "
